# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jared Woytas Resume
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  I am passionate about technology and am always interested in learning
  new skills to increase my productivity.  
baseurl: "/resume/" # the subpath of your site, e.g. /blog
url: "https://jwoytas.github.io/resume" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  jwoytas


# Build settings
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
show_downloads: false

name: Jared Woytas
email: jwoytas@gmail.com
email_full: mailto:jwoytas@gmail.com
github_site: jwoytas.github.io

# website: github.io/sustain
# website_full: https://jekyller.github.io/sustain